#!/usr/bin/env bash
set -euo pipefail

# recollection-export.sh
# Generates a SOPHY hourly recollection markdown and commits it to the repo.

TIMESTAMP="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
OUTDIR=".sophy/recollections"
mkdir -p "$OUTDIR"
FILENAME="$OUTDIR/SOPHY_HOURLY_RECOLLECTION_${TIMESTAMP//:/_}.md"

cat > "$FILENAME" <<EOF
# SOPHY_HOURLY_RECOLLECTION — $TIMESTAMP

**Auto-generated hourly recollection**

- timestamp_utc: $TIMESTAMP
- note: This file was auto-generated by the SOPHY recollection workflow.

EOF

# Commit changes
git config user.name "sophy-bot"
git config user.email "sophy-bot@example.com"

# Create branch
BRANCH="sophy/recollections/auto-${TIMESTAMP//:/_}"

# Use git CLI to create branch from current HEAD

git checkout -b "$BRANCH"

git add "$FILENAME"
git commit -m "SOPHY hourly recollection: $TIMESTAMP"

git push origin "$BRANCH"

echo "WROTE $FILENAME and pushed branch $BRANCH"
